services:
  - type: web
    name: eren-bingo
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: HOST_KEY
        sync: false
      - key: DEFAULT_ROOM
        value: anaoda
      - key: CLAIM_TTL_MS
        value: 10000
